# Common build definition using YAML anchors
x-node-build: &node-build
  build:
    context: .
    dockerfile: Dockerfile

services:
  node1:
    <<: *node-build # Use the common build definition
    image: p2p-node-image # Standardize image name
    volumes:
      - ./identities/node1_config.yaml:/app/config.yaml:ro # Mount specific config read-only
    environment:
      - NODE_NAME=node1
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
      # Add other necessary environment variables
    network_mode: host # Use host network for direct connection to dfx
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node2:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node2_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node2
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node3:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node3_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node3
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node4:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node4_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node4
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node5:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node5_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node5
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node6:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node6_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node6
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node7:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node7_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node7
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node8:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node8_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node8
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node9:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node9_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node9
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node10:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node10_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node10
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node11:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node11_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node11
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node12:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node12_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node12
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node13:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node13_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node13
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node14:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node14_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node14
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node15:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node15_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node15
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node16:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node16_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node16
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node17:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node17_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node17
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node18:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node18_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node18
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node19:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node19_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node19
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

  node20:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node20_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node20
      - RUST_LOG=info,libp2p_gossipsub=debug # Enable gossipsub debug logs
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p" # Add sleep before starting

volumes:
  ic_state:

# Removed the unused networks section 