version: '3.8'

# Define the build for the common node image
x-node-build: &node-build
  build:
    context: .
    dockerfile: Dockerfile

services:
  node1:
    <<: *node-build # Use the common build definition
    image: p2p-node-image # Standardize image name
    volumes:
      - node1_data:/app/data
    environment:
      - NODE_NAME=node1
      - RUST_LOG=debug
      - IC_URL=http://127.0.0.1:4943
    network_mode: host # Use host network

  node2:
    image: p2p-node-image # Standardize image name
    volumes:
      - node2_data:/app/data
    environment:
      - NODE_NAME=node2
      - RUST_LOG=debug
      - IC_URL=http://127.0.0.1:4943
    network_mode: host # Use host network

  node3:
    image: p2p-node-image # Standardize image name
    volumes:
      - node3_data:/app/data
    environment:
      - NODE_NAME=node3
      - RUST_LOG=debug
      - IC_URL=http://127.0.0.1:4943
    network_mode: host # Use host network

  node4:
    image: p2p-node-image # Standardize image name
    volumes:
      - node4_data:/app/data
    environment:
      - NODE_NAME=node4
      - RUST_LOG=debug
      - IC_URL=http://127.0.0.1:4943
    network_mode: host # Use host network

  node5:
    image: p2p-node-image # Standardize image name
    volumes:
      - node5_data:/app/data
    environment:
      - NODE_NAME=node5
      - RUST_LOG=debug
      - IC_URL=http://127.0.0.1:4943
    network_mode: host # Use host network

  node6:
    image: p2p-node-image # Standardize image name
    volumes:
      - node6_data:/app/data
    environment:
      - NODE_NAME=node6
      - RUST_LOG=debug
      - IC_URL=http://127.0.0.1:4943
    network_mode: host # Use host network

  node7:
    image: p2p-node-image # Standardize image name
    volumes:
      - node7_data:/app/data
    environment:
      - NODE_NAME=node7
      - RUST_LOG=debug
      - IC_URL=http://127.0.0.1:4943
    network_mode: host # Use host network

  node8:
    image: p2p-node-image # Standardize image name
    volumes:
      - node8_data:/app/data
    environment:
      - NODE_NAME=node8
      - RUST_LOG=debug
      - IC_URL=http://127.0.0.1:4943
    network_mode: host # Use host network

  node9:
    image: p2p-node-image # Standardize image name
    volumes:
      - node9_data:/app/data
    environment:
      - NODE_NAME=node9
      - RUST_LOG=debug
      - IC_URL=http://127.0.0.1:4943
    network_mode: host # Use host network

  node10:
    image: p2p-node-image # Standardize image name
    volumes:
      - node10_data:/app/data
    environment:
      - NODE_NAME=node10
      - RUST_LOG=debug
      - IC_URL=http://127.0.0.1:4943
    network_mode: host # Use host network

volumes:
  node1_data:
  node2_data:
  node3_data:
  node4_data:
  node5_data:
  node6_data:
  node7_data:
  node8_data:
  node9_data:
  node10_data:
  ic_state:

# Removed the unused networks section 