# Common build definition using YAML anchors
x-node-build: &node-build
  build:
    context: .
    dockerfile: Dockerfile

services:
  node1:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node1_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node1
      - RUST_LOG=info
      - MDNS_PORT=5354
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p"

  node2:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node2_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node2
      - RUST_LOG=info
      - MDNS_PORT=5355
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p"

  node3:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node3_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node3
      - RUST_LOG=info
      - MDNS_PORT=5356
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p"

  node4:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node4_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node4
      - RUST_LOG=info
      - MDNS_PORT=5357
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p"

  node5:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node5_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node5
      - RUST_LOG=info
      - MDNS_PORT=5358
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p"

  node6:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node6_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node6
      - RUST_LOG=info
      - MDNS_PORT=5359
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p"

  node7:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node7_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node7
      - RUST_LOG=info
      - MDNS_PORT=5360
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p"

  node8:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node8_config.yaml:/app/config.yaml:ro
    environment:
      - NODE_NAME=node8
      - RUST_LOG=info
      - MDNS_PORT=5361
    network_mode: host
    command: sh -c "sleep 5 && /app/p2p"

volumes:
  ic_state:

# Removed the unused networks section 