version: '3.8'

services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node1_data:/app/data
    environment:
      - NODE_NAME=node1
      - RUST_LOG=debug
      - IC_URL=http://192.168.100.172:49517
    networks:
      - p2p_network

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node2_data:/app/data
    environment:
      - NODE_NAME=node2
      - RUST_LOG=debug
      - IC_URL=http://192.168.100.172:49517
    networks:
      - p2p_network

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node3_data:/app/data
    environment:
      - NODE_NAME=node3
      - RUST_LOG=debug
      - IC_URL=http://192.168.100.172:49517
    networks:
      - p2p_network

  node4:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node4_data:/app/data
    environment:
      - NODE_NAME=node4
      - RUST_LOG=debug
      - IC_URL=http://192.168.100.172:49517
    networks:
      - p2p_network

  node5:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node5_data:/app/data
    environment:
      - NODE_NAME=node5
      - RUST_LOG=debug
      - IC_URL=http://192.168.100.172:49517
    networks:
      - p2p_network

  node6:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node6_data:/app/data
    environment:
      - NODE_NAME=node6
      - RUST_LOG=debug
      - IC_URL=http://192.168.100.172:49517
    networks:
      - p2p_network

  node7:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node7_data:/app/data
    environment:
      - NODE_NAME=node7
      - RUST_LOG=debug
      - IC_URL=http://192.168.100.172:49517
    networks:
      - p2p_network

  node8:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node8_data:/app/data
    environment:
      - NODE_NAME=node8
      - RUST_LOG=debug
      - IC_URL=http://192.168.100.172:49517
    networks:
      - p2p_network

  node9:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node9_data:/app/data
    environment:
      - NODE_NAME=node9
      - RUST_LOG=debug
      - IC_URL=http://192.168.100.172:49517
    networks:
      - p2p_network

  node10:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node10_data:/app/data
    environment:
      - NODE_NAME=node10
      - RUST_LOG=debug
      - IC_URL=http://192.168.100.172:49517
    networks:
      - p2p_network

volumes:
  node1_data:
  node2_data:
  node3_data:
  node4_data:
  node5_data:
  node6_data:
  node7_data:
  node8_data:
  node9_data:
  node10_data:
  ic_state:

networks:
  p2p_network:
    driver: bridge 