node:
  name: "node2"
  port: 33334
  private_key: "da66c31e668195f1078c1b835ef0e7e4dee2e2ad6bd85bca3fec5034219a495f"
  ic:
    network: "local"
    canister_id: "c5kvi-uuaaa-aaaaa-qaaia-cai"
    is_local: true
    url: "http://192.168.1.60:49517"
  peer_nodes: []
