node:
  name: "node63"
  port: 33397
  private_key: "72592fa4bede3243b94fe10a2e038676aa5e9ced90a696855636a5d8aabe9215"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
