node:
  name: "node11"
  port: 33345
  private_key: "a308054b39697b3ba73f44a59f2797e25d3de85edcd76929edd3395874e0e606"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
