node:
  name: "node54"
  port: 33388
  private_key: "63be06f145a198d51010dfc9a21af1ee3ccbdd47b0dd8341c18af06170b7c58d"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
