node:
  name: "node92"
  port: 33426
  private_key: "ae2eba01a21a597d67a86041c120c4568dacf799cec8355b44fdc3205e73852f"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
