node:
  name: "node22"
  port: 33356
  private_key: "ef08a80e1c9cb5cee7303e349c47e2faff83e9d56d6c2726ca19bedbc4686c2c"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
