node:
  name: "node27"
  port: 33361
  private_key: "af369321fd2536e6c0fcfba698ffb648fe59b7b004693be4e94c4d7c55857f40"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
