node:
  name: "node25"
  port: 33359
  private_key: "9a9d5b117f258af914a648aae53bcddfccdeb912b15805b570b36509e1ee97a6"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
