node:
  name: "node44"
  port: 33378
  private_key: "c3092fc52b308e2ccafe35b675d4c92d2395ef3b143cefcbb4160b1df8c77ece"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
