node:
  name: "node14"
  port: 33348
  private_key: "3bef9ad7f99159302e821deae42a60f9bbad80bd73ec3f4608e59399668d1392"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
