node:
  name: "node39"
  port: 33373
  private_key: "c388afcfe832ec1f50fe7d07c0c241ee9ac4f20922400e087f173a9962b3c56b"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
