node:
  name: "node24"
  port: 33358
  private_key: "3bfc4e7d7436c3ab68fb3aac81a44fe08cae04acaf844bd14295f7d7b1a5640c"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
