node:
  name: "node2"
  port: 4002
  private_key: "e9a8b0307f9068b9827316a8c34c9211a16a9126c95f10e578951b3747f8f049"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
