node:
  name: "node5"
  port: 4005
  private_key: "2447585fa0b58094e09a682aeb36fc59033f3a0210246ddbd089e472891f0776"
  ic:
    network: "local"
    canister_id: ""
    is_local: true
    url: "http://ic_replica:4943"
  peer_nodes: []
