node:
  name: "node87"
  port: 33421
  private_key: "8af56c8cfa433452281d0c62a0ab43c5a9d1877cf1264ddcf346b0c9ba7cb61b"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
