node:
  name: "node16"
  port: 33350
  private_key: "1a346b748f56018f835a5b27ceb95922728cc6b0a997cbe4a534053ed27379c2"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
