node:
  name: "node12"
  port: 33346
  private_key: "3438cc50984fa3b00b01693bf31e7a1e9f55411068a66be6cd7c5e6efc239679"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
