node:
  name: "node1"
  port: 4001
  private_key: "26b6415b6ab4db09e12471ff864e6c10dd42fd954e60103a1418f80dfc5c4cbc"
  ic:
    network: "local"
    canister_id: ""
    is_local: true
    url: "http://ic_replica:4943"
  peer_nodes: []
