node:
  name: "node7"
  port: 4007
  private_key: "b62e2113b07d5a9fbd16f6e2de0000e6aeae1ae3cf23487e8538673ee4d49fa6"
  ic:
    network: "local"
    canister_id: ""
    is_local: true
    url: "http://ic_replica:4943"
  peer_nodes: []
