node:
  name: "node20"
  port: 33354
  private_key: "cdcc79d51ef028063fcc27e345d46678243cb9b87c8c1ce3c3e1ba3e8131c44a"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
