node:
  name: "node93"
  port: 33427
  private_key: "293fe65171651086422b0a45e18412b9d350ec68eca4d4099bbccaa8d5dab0a5"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
