node:
  name: "node9"
  port: 33343
  private_key: "95d173ea0c829ed5cd9c510a5b94ecdf9032f2466d2d70621a97de423dc504b3"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
