node:
  name: "node17"
  port: 33351
  private_key: "cbd65d8d51dbe0e5a0c518015b1cdd3794b83cd2fef4c360212a2a33fb5e078a"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
