node:
  name: "node15"
  port: 33349
  private_key: "0308358fb023a6ee84e5a98cf4d6913cc8766488a2b57ec561b9b08b16dec2b9"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
