node:
  name: "node99"
  port: 33433
  private_key: "200102719c9150fb031770d2c5d64cb357f80882e85eb3ef828da12394919ced"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
