node:
  name: "node10"
  port: 33344
  private_key: "9d8810d9ebd5f1229a045d304ea2e7f46da599eefee10b8816c8e52fd5d7181f"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://192.168.100.172:49517"
  peer_nodes: []
