node:
  name: "node4"
  port: 4004
  private_key: "2a3d6d255883ec105fd7238f2a46d36f61d64b3b8828d1e228e4db8fbcf3c0d8"
  ic:
    network: "local"
    canister_id: ""
    is_local: true
    url: "http://ic_replica:4943"
  peer_nodes: []
