node:
  name: "node3"
  port: 33337
  private_key: "e13a46456512c168866a9ea4b385df125d66ca13a11499e6de023eefdca70f9d"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
