node:
  name: "node73"
  port: 33407
  private_key: "fdcbc5d3230c8a77bbe5b21e4edfd46db1e7d9ec6cd1ccfab408193e19a2ca56"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
