node:
  name: "node95"
  port: 33429
  private_key: "be9e487b82735e8fba49fed267fa0ac511056cfa408f96b4652ab99bba837f26"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
