node:
  name: "node89"
  port: 33423
  private_key: "d94cb22b8eb8fdae0e12b9c78fa3329cf24bd229485f723b0c8e2b539b9999d4"
  ic:
    network: "local"
    canister_id: "bkyz2-fmaaa-aaaaa-qaaaq-cai"
    is_local: true
    url: "http://127.0.0.1:4943"
  peer_nodes: []
